import type { Recipe } from "../../../hooks/useRecipes";

const mockFavouriteRecipes: Recipe[] = [
  {
    id: 1,
    title: "Spaghetti Carbonara",
    image: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800",
    category: "Pasta",
    cuisine: "Italian",
    cook_time: 20,
    prep_time: 10,
    ratings: 4.8,
    author: "Marco Rossi",
    ingredients: [
      { id: 1, name: "Spaghetti" },
      { id: 2, name: "Pancetta" },
      { id: 3, name: "Eggs" },
      { id: 4, name: "Pecorino Romano" },
      { id: 5, name: "Black pepper" },
    ],
  },
  {
    id: 2,
    title: "Chicken Tikka Masala",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800",
    category: "Curry",
    cuisine: "Indian",
    cook_time: 40,
    prep_time: 20,
    ratings: 4.7,
    author: "Priya Sharma",
    ingredients: [
      { id: 6, name: "Chicken breast" },
      { id: 7, name: "Tomato sauce" },
      { id: 8, name: "Heavy cream" },
      { id: 9, name: "Garam masala" },
      { id: 10, name: "Ginger" },
      { id: 11, name: "Garlic" },
    ],
  },
  {
    id: 3,
    title: "Classic French Omelette",
    image: "https://images.unsplash.com/photo-1510693206972-df098062cb71?w=800",
    category: "Breakfast",
    cuisine: "French",
    cook_time: 5,
    prep_time: 5,
    ratings: 4.5,
    author: "Sophie Dupont",
    ingredients: [
      { id: 12, name: "Eggs" },
      { id: 13, name: "Butter" },
      { id: 14, name: "Chives" },
      { id: 15, name: "Salt" },
    ],
  },
  {
    id: 4,
    title: "Beef Tacos",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800",
    category: "Street Food",
    cuisine: "Mexican",
    cook_time: 20,
    prep_time: 15,
    ratings: 4.6,
    author: "Carlos Mendez",
    ingredients: [
      { id: 16, name: "Ground beef" },
      { id: 17, name: "Corn tortillas" },
      { id: 18, name: "Onion" },
      { id: 19, name: "Cilantro" },
      { id: 20, name: "Lime" },
      { id: 21, name: "Cumin" },
    ],
  },
  {
    id: 5,
    title: "Avocado Toast",
    image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=800",
    category: "Breakfast",
    cuisine: "American",
    cook_time: 5,
    prep_time: 5,
    ratings: 4.3,
    author: "Emma Walsh",
    ingredients: [
      { id: 22, name: "Sourdough bread" },
      { id: 23, name: "Avocado" },
      { id: 24, name: "Lemon juice" },
      { id: 25, name: "Chili flakes" },
      { id: 26, name: "Sea salt" },
    ],
  },
  {
    id: 6,
    title: "Greek Salad",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800",
    category: "Salad",
    cuisine: "Greek",
    cook_time: 0,
    prep_time: 15,
    ratings: 4.4,
    author: "Nikos Papadopoulos",
    ingredients: [
      { id: 27, name: "Tomatoes" },
      { id: 28, name: "Cucumber" },
      { id: 29, name: "Kalamata olives" },
      { id: 30, name: "Feta cheese" },
      { id: 31, name: "Red onion" },
      { id: 32, name: "Olive oil" },
    ],
  },
  {
    id: 7,
    title: "Ramen Noodle Soup",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800",
    category: "Soup",
    cuisine: "Japanese",
    cook_time: 180,
    prep_time: 30,
    ratings: 4.9,
    author: "Yuki Tanaka",
    ingredients: [
      { id: 33, name: "Ramen noodles" },
      { id: 34, name: "Pork belly" },
      { id: 35, name: "Soft-boiled eggs" },
      { id: 36, name: "Nori" },
      { id: 37, name: "Soy sauce" },
      { id: 38, name: "Mirin" },
      { id: 39, name: "Green onions" },
    ],
  },
  {
    id: 8,
    title: "Chocolate Lava Cake",
    image: "https://images.unsplash.com/photo-1617305855058-336d24456869?w=800",
    category: "Dessert",
    cuisine: "French",
    cook_time: 12,
    prep_time: 15,
    ratings: 4.9,
    author: "Pierre Lambert",
    ingredients: [
      { id: 40, name: "Dark chocolate" },
      { id: 41, name: "Butter" },
      { id: 42, name: "Eggs" },
      { id: 43, name: "Sugar" },
      { id: 44, name: "Flour" },
      { id: 45, name: "Vanilla extract" },
    ],
  },
];

export default mockFavouriteRecipes;
