version: "3.8"

services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/rails
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:password@db/my_recipes_development
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        ./bin/rails db:prepare &&
        ./bin/rails s -b 0.0.0.0
      "

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - api

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: my_recipes_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
